### ISSUE TITLE
Missing source files

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Roboto-Flex#150]
If I attempt to generate the fonts, I get the following traceback:

```
(venv) Marcs-Air-2:Roboto-Flex marcfoley$ sh sources/build-roboto.sh 
Build fonts…
/Users/marcfoley/Type/upstream_repos/Roboto-Flex/sources/build-roboto.py:15: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.dir_util import copy_tree
Cleaning up...
Reading DesignSpace...
Building masters...
Traceback (most recent call last):
  File "/Users/marcfoley/Type/upstream_repos/Roboto-Flex/sources/build-roboto.py", line 816, in <module>
    font = Font(source_path)
  File "/Users/marcfoley/Type/upstream_repos/Roboto-Flex/venv/lib/python3.10/site-packages/defcon/objects/font.py", line 148, in __init__
    reader = UFOReader(self._path, validate=self.ufoLibReadValidate)
  File "/Users/marcfoley/Type/upstream_repos/Roboto-Flex/venv/lib/python3.10/site-packages/fontTools/ufoLib/__init__.py", line 211, in __init__
    structure = _sniffFileStructure(path)
  File "/Users/marcfoley/Type/upstream_repos/Roboto-Flex/venv/lib/python3.10/site-packages/fontTools/ufoLib/__init__.py", line 1712, in _sniffFileStructure
    raise UFOLibError("No such file or directory: '%s'" % ufo_path)
fontTools.ufoLib.errors.UFOLibError: No such file or directory: 'sources/1-drawings/RobotoFlex-opsz144-wght1000.ufo'

```

Seems there are some ufos missing.

cc @sannorozco

**Comment by m4rc1e** [comment]
It doesn't exist in a different dir either 

`$ find . -type 'd' -iname "RobotoFlex-opsz144-wght1000.ufo"`

returns nothing.

**Comment by sannorozco** [comment]
Added missing source file.

**Comment by dberlow** [comment]
I’m going to need to respond to Dave for this — so did this happened because you were waiting to interpolate that source file to correct the ° and for some reason it was missing temporary?

On Jan 26, 2022, at 11:45 AM, Santiago Orozco ***@***.***> wrote:

﻿
Added missing source file.
